### ISSUE TITLE
运行报错 Unexpected identifier

### ISSUE THREAD

**Issue by lzuliuyun** [lhlybly/node_12306#4]
按照步骤，修改账户密码，运行报错。

![image](https://cloud.githubusercontent.com/assets/6896562/21955309/99dd2e08-daa3-11e6-9cd2-ead820d04197.png)

**Comment by hongrunhui** [comment]
把后面注释去掉看看

**Comment by hongrunhui** [comment]
兄台你看看代码里是不是少了个逗号，
![image](https://cloud.githubusercontent.com/assets/9162319/21960214/09127976-db1d-11e6-8e6e-ab80281431a7.png)
如果不是的话，是不是你的邮箱格式有问题？

**Comment by hongrunhui** [comment]
应该就是逗号的问题，我之前上传代码的时候可能不小心把这个逗号给去了，你现在git pull 一下应该没有这个问题了。
