### ISSUE TITLE
有时报错，导致程序退出？

### ISSUE THREAD

**Issue by lightCraft2020** [lhlybly/node_12306#5]
![bug](https://cloud.githubusercontent.com/assets/11204164/21962781/12f5f3fe-db69-11e6-97b5-e3eb924f77dc.png)

**Comment by hongrunhui** [comment]
这种错误可以忽略，你安装pm2来启动这个程序吧，退出后会自动重启：
```npm install pm2 -g```安装
```[sudo] pm2 start -w main.js```启动
```[sudo] pm2 list``` 查看

**Comment by lightCraft2020** [comment]
不错，非常感谢！
