### ISSUE TITLE
如果检测到的确有余票，但是这个时候你去登录12306的过程中会有时间误差，如何保证能正常下单？

### ISSUE THREAD

**Issue by strongant** [lhlybly/node_12306#6]

**Comment by hongrunhui** [comment]
这个功能还没做，但是如果你登上去发现票已经被抢了，那就再等下一个，总有一次能抢到的。因为我经常在电脑旁，所以只要一发邮件来我就登录，虽然说有间隔，但是除了有其他抢票软件在抢这辆车或者正好有人在12306上查询这辆车（这个几率很小），一般人是没我快的。所以我抢了3张票。

**Comment by qizhenjiang** [comment]
@hongrunhui    你的这个   一分钟访问一次  太慢了  在哪里把这个时间调快点    谢谢

**Comment by hongrunhui** [comment]
```rule.second = [0,15,30,45,60];```这个应该是15s访问一次。

**Comment by strongant** [comment]
那还不错
